### ISSUE TITLE
[Meta] Roadmap for Initial Package Release

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#13]
Now that initial linting capability is good to go (#5), the package needs some cleaning before it's ready to go up on PyPi and into production. Because the package started as an AST parsing experiment, there's a decent bit of "this code looks like someone stumbling through how to write a flake8 plugin" because, well, I was stumbling through figuring out how to write a flake8 plugin (e.g. #12).

Here's an initial summary of tasks:

- [x] Settle on a name
- [x] Add support for ignoring errors via `.flake8` & similar (#8)
- [x] Add support for inline `# noqa` (#8)
- [x] Profile code & refactor as necessary to streamline inefficiencies
- [x] Update `__repr__` and `__str__` methods, where appropriate, to provide proper (non-debugging) strings (#7, #27)
- [x] Write unit tests & generate testing files (#16, #27)
- [x] Generate comprehensive documentation (#19)
- [x] Generate CI pipelines (#17, #27)
- [x] Lock in package name on PyPi
- [x] Settle on a versioning scheme (#24)
- [x] Add webhook to Discord
- [ ] Any misc. bugfixes/enhancements that come up before the above tasks are complete

Initial PyPi release will be `1.0.0`, we'll need to archive the current version (`2019.0`) once we hit our initial release to avoid conflict.
